version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./services/backend/src/static:/static
    depends_on:
      - backend
      - dash_app
    networks:
      - app-network

  backend:
    build: ./services/backend
    command: gunicorn --config gunicorn.conf.py config.wsgi:application
    env_file:
      - .env
    volumes:
      - ./services/backend/src:/app/src
    depends_on:
      - db
    networks:
      - app-network

  dash_app:
    build: ./services/dash_app
    command: gunicorn app:server -b 0.0.0.0:8050
    env_file:
      - .env
    networks:
      - app-network

  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
