version: '3.8'

services:
db:
image: postgres:13
volumes:
- postgres_data:/var/lib/postgresql/data/
environment:
POSTGRES_DB: ${DB_NAME}
POSTGRES_USER: ${DB_USER}
POSTGRES_PASSWORD: ${DB_PASSWORD}
networks:
- backend-network

backend:
build: ./services/backend
command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
volumes:
- ./services/backend/src:/app
environment:
- SECRET_KEY=${SECRET_KEY}
- DB_NAME=${DB_NAME}
- DB_USER=${DB_USER}
- DB_PASSWORD=${DB_PASSWORD}
- DB_HOST=db
- DB_PORT=5432
depends_on:
- db
networks:
- backend-network

dash_app:
build: ./services/dash_app
command: gunicorn app:server --bind 0.0.0.0:8050
volumes:
- ./services/dash_app/src:/app
environment:
- DB_NAME=${DB_NAME}
- DB_USER=${DB_USER}
- DB_PASSWORD=${DB_PASSWORD}
- DB_HOST=db
- DB_PORT=5432
depends_on:
- db
networks:
- backend-network

nginx:
image: nginx:latest
ports:
- "80:80"
volumes:
- ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
- ./services/backend/src/static:/static
depends_on:
- backend
- dash_app
networks:
- backend-network

networks:
backend-network:
driver: bridge

volumes:
postgres_data:
